name: Release Docker

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    environment:
      name: Docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/arne-vl/telegram-approval-bot:${{ env.VERSION }}
          docker tag ghcr.io/arne-vl/telegram-approval-bot:${{ env.VERSION }} ghcr.io/arne-vl/telegram-approval-bot:latest

      - name: Push Image to GHCR
        run: |
          docker push ghcr.io/arne-vl/telegram-approval-bot:${{ env.VERSION }}

      - name: Push Latest Image to GHCR
        run: |
          docker push ghcr.io/arne-vl/telegram-approval-bot:latest

      - name: Create GitHub release
        run: |
          gh release create ${{ env.VERSION }} --title "${{ env.VERSION }}" --notes "Release ${GITHUB_REF#refs/tags/}" --target ${{ github.sha }} --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
